// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SKDJK.Data;

#nullable disable

namespace SKDJK.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260820104854_MakeTopicLevelUnicode")]
    partial class MakeTopicLevelUnicode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SKDJK.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("answers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 20101,
                            Content = "She is checking in at a hotel.",
                            IsCorrect = true,
                            QuestionId = 10101
                        },
                        new
                        {
                            Id = 20102,
                            Content = "She is driving a bus.",
                            IsCorrect = false,
                            QuestionId = 10101
                        },
                        new
                        {
                            Id = 20103,
                            Content = "She is cooking dinner.",
                            IsCorrect = false,
                            QuestionId = 10101
                        },
                        new
                        {
                            Id = 20104,
                            Content = "At three o'clock.",
                            IsCorrect = true,
                            QuestionId = 10102
                        },
                        new
                        {
                            Id = 20105,
                            Content = "Yes, I can see it.",
                            IsCorrect = false,
                            QuestionId = 10102
                        },
                        new
                        {
                            Id = 20106,
                            Content = "For two people.",
                            IsCorrect = false,
                            QuestionId = 10102
                        },
                        new
                        {
                            Id = 20107,
                            Content = "At the station.",
                            IsCorrect = true,
                            QuestionId = 10103
                        },
                        new
                        {
                            Id = 20108,
                            Content = "Next Monday.",
                            IsCorrect = false,
                            QuestionId = 10103
                        },
                        new
                        {
                            Id = 20109,
                            Content = "By email.",
                            IsCorrect = false,
                            QuestionId = 10103
                        },
                        new
                        {
                            Id = 20110,
                            Content = "A change to the train schedule.",
                            IsCorrect = true,
                            QuestionId = 10104
                        },
                        new
                        {
                            Id = 20111,
                            Content = "A restaurant opening.",
                            IsCorrect = false,
                            QuestionId = 10104
                        },
                        new
                        {
                            Id = 20112,
                            Content = "A job interview.",
                            IsCorrect = false,
                            QuestionId = 10104
                        },
                        new
                        {
                            Id = 20113,
                            Content = "reviews",
                            IsCorrect = true,
                            QuestionId = 10105
                        },
                        new
                        {
                            Id = 20114,
                            Content = "review",
                            IsCorrect = false,
                            QuestionId = 10105
                        },
                        new
                        {
                            Id = 20115,
                            Content = "reviewing",
                            IsCorrect = false,
                            QuestionId = 10105
                        },
                        new
                        {
                            Id = 20116,
                            Content = "complete",
                            IsCorrect = true,
                            QuestionId = 10106
                        },
                        new
                        {
                            Id = 20117,
                            Content = "fill in",
                            IsCorrect = true,
                            QuestionId = 10106
                        },
                        new
                        {
                            Id = 20118,
                            Content = "From 6:30 a.m. to 10:00 a.m.",
                            IsCorrect = true,
                            QuestionId = 10107
                        },
                        new
                        {
                            Id = 20119,
                            Content = "At noon.",
                            IsCorrect = false,
                            QuestionId = 10107
                        },
                        new
                        {
                            Id = 20120,
                            Content = "Only on weekends.",
                            IsCorrect = false,
                            QuestionId = 10107
                        },
                        new
                        {
                            Id = 20201,
                            Content = "A single room",
                            IsCorrect = true,
                            QuestionId = 10201
                        },
                        new
                        {
                            Id = 20202,
                            Content = "A conference room",
                            IsCorrect = false,
                            QuestionId = 10201
                        },
                        new
                        {
                            Id = 20203,
                            Content = "A family suite",
                            IsCorrect = false,
                            QuestionId = 10201
                        },
                        new
                        {
                            Id = 20204,
                            Content = "five",
                            IsCorrect = true,
                            QuestionId = 10202
                        },
                        new
                        {
                            Id = 20205,
                            Content = "5",
                            IsCorrect = true,
                            QuestionId = 10202
                        },
                        new
                        {
                            Id = 20206,
                            Content = "Environmental science",
                            IsCorrect = true,
                            QuestionId = 10203
                        },
                        new
                        {
                            Id = 20207,
                            Content = "Modern history",
                            IsCorrect = false,
                            QuestionId = 10203
                        },
                        new
                        {
                            Id = 20208,
                            Content = "Business law",
                            IsCorrect = false,
                            QuestionId = 10203
                        },
                        new
                        {
                            Id = 20209,
                            Content = "energy",
                            IsCorrect = true,
                            QuestionId = 10204
                        },
                        new
                        {
                            Id = 20210,
                            Content = "TRUE",
                            IsCorrect = false,
                            QuestionId = 10205
                        },
                        new
                        {
                            Id = 20211,
                            Content = "FALSE",
                            IsCorrect = false,
                            QuestionId = 10205
                        },
                        new
                        {
                            Id = 20212,
                            Content = "NOT GIVEN",
                            IsCorrect = true,
                            QuestionId = 10205
                        },
                        new
                        {
                            Id = 20213,
                            Content = "YES",
                            IsCorrect = true,
                            QuestionId = 10206
                        },
                        new
                        {
                            Id = 20214,
                            Content = "NO",
                            IsCorrect = false,
                            QuestionId = 10206
                        },
                        new
                        {
                            Id = 20215,
                            Content = "NOT GIVEN",
                            IsCorrect = false,
                            QuestionId = 10206
                        },
                        new
                        {
                            Id = 20216,
                            Content = "electricity",
                            IsCorrect = true,
                            QuestionId = 10207
                        });
                });

            modelBuilder.Entity("SKDJK.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasDefaultValue("English");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 10001,
                            Code = "en-demo",
                            Description = "Ngôn ngữ dùng cho dữ liệu demo TOEIC/IELTS-style.",
                            Name = "Tiếng Anh"
                        },
                        new
                        {
                            Id = 10002,
                            Code = "ja-demo",
                            Description = "Ngôn ngữ mẫu bổ sung.",
                            Name = "Tiếng Nhật"
                        });
                });

            modelBuilder.Entity("SKDJK.Models.LearningProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CompletionPercent")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("LastStudyAt")
                        .HasColumnType("Datetime2");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasDefaultValue("NOTSTARTED");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("learningprogresses", (string)null);
                });

            modelBuilder.Entity("SKDJK.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("lessons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 10001,
                            Content = "Thì hiện tại đơn được dùng để nói về thói quen và sự thật. Cấu trúc: S + V(s/es). Ví dụ: She books a room online.",
                            Description = "Học từ vựng và mẫu câu đặt phòng.",
                            Title = "Đặt phòng khách sạn",
                            TopicId = 10001
                        },
                        new
                        {
                            Id = 10002,
                            Content = "Dùng Can you tell me...? hoặc How can I get to...? để hỏi đường một cách lịch sự.",
                            Description = "Hỏi đường, vị trí và phương tiện đi lại.",
                            Title = "Hỏi đường và phương tiện",
                            TopicId = 10001
                        },
                        new
                        {
                            Id = 10003,
                            Content = "Dùng hiện tại đơn để mô tả công việc thường ngày và lịch làm việc.",
                            Description = "Từ vựng văn phòng cơ bản.",
                            Title = "Giao tiếp tại nơi làm việc",
                            TopicId = 10002
                        },
                        new
                        {
                            Id = 10004,
                            Content = "こんにちは được dùng để chào hỏi vào ban ngày.",
                            Description = "Các lời chào thông dụng.",
                            Title = "Lời chào cơ bản",
                            TopicId = 10003
                        });
                });

            modelBuilder.Entity("SKDJK.Models.PronunciationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VocabularyId");

                    b.ToTable("pronunciationresults", (string)null);
                });

            modelBuilder.Entity("SKDJK.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContextText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("PartNumber")
                        .HasColumnType("int");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("questions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 10101,
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                            Content = "What is the person doing?",
                            GroupCode = "T-P1",
                            ImageUrl = "/images/toeic-part1.svg",
                            Order = 1,
                            PartNumber = 1,
                            QuestionType = "ListeningChoice",
                            SectionName = "Listening",
                            TestId = 10001
                        },
                        new
                        {
                            Id = 10102,
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                            Content = "Choose the best response to the recorded question.",
                            GroupCode = "T-P2",
                            Order = 2,
                            PartNumber = 2,
                            QuestionType = "ListeningChoice",
                            SectionName = "Listening",
                            TestId = 10001
                        },
                        new
                        {
                            Id = 10103,
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                            Content = "Where will the speakers meet?",
                            GroupCode = "T-P3",
                            Order = 3,
                            PartNumber = 3,
                            QuestionType = "ListeningChoice",
                            SectionName = "Listening",
                            TestId = 10001
                        },
                        new
                        {
                            Id = 10104,
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                            Content = "What is the announcement mainly about?",
                            GroupCode = "T-P4",
                            Order = 4,
                            PartNumber = 4,
                            QuestionType = "ListeningChoice",
                            SectionName = "Listening",
                            TestId = 10001
                        },
                        new
                        {
                            Id = 10105,
                            Content = "The manager _____ the report every Monday.",
                            Order = 5,
                            PartNumber = 5,
                            QuestionType = "MultipleChoice",
                            SectionName = "Reading",
                            TestId = 10001
                        },
                        new
                        {
                            Id = 10106,
                            Content = "Complete the text: Please _____ the attached form.",
                            ContextText = "Thank you for your interest. Please _____ the attached form before Friday.",
                            GroupCode = "T-P6",
                            Order = 6,
                            PartNumber = 6,
                            QuestionType = "FillBlank",
                            SectionName = "Reading",
                            TestId = 10001
                        },
                        new
                        {
                            Id = 10107,
                            Content = "When does the hotel serve breakfast?",
                            ContextText = "Breakfast is served from 6:30 a.m. to 10:00 a.m. in the first-floor restaurant.",
                            GroupCode = "T-P7",
                            Order = 7,
                            PartNumber = 7,
                            QuestionType = "MultipleChoice",
                            SectionName = "Reading",
                            TestId = 10001
                        },
                        new
                        {
                            Id = 10201,
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                            Content = "What type of room does the caller request?",
                            GroupCode = "I-L1",
                            Order = 1,
                            PartNumber = 1,
                            QuestionType = "ListeningChoice",
                            SectionName = "Listening",
                            TestId = 10002
                        },
                        new
                        {
                            Id = 10202,
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                            Content = "The museum closes at ____ p.m.",
                            GroupCode = "I-L2",
                            Order = 2,
                            PartNumber = 2,
                            QuestionType = "ListeningFill",
                            SectionName = "Listening",
                            TestId = 10002
                        },
                        new
                        {
                            Id = 10203,
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                            Content = "Which subject are the students discussing?",
                            GroupCode = "I-L3",
                            Order = 3,
                            PartNumber = 3,
                            QuestionType = "ListeningChoice",
                            SectionName = "Listening",
                            TestId = 10002
                        },
                        new
                        {
                            Id = 10204,
                            AudioUrl = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
                            Content = "The lecture focuses on renewable ____.",
                            GroupCode = "I-L4",
                            Order = 4,
                            PartNumber = 4,
                            QuestionType = "ListeningFill",
                            SectionName = "Listening",
                            TestId = 10002
                        },
                        new
                        {
                            Id = 10205,
                            Content = "The library opens every Sunday.",
                            ContextText = "The city library opens Monday to Saturday. The notice gives no information about Sunday opening.",
                            GroupCode = "I-R1",
                            Order = 5,
                            PartNumber = 1,
                            QuestionType = "TrueFalseNotGiven",
                            SectionName = "Reading",
                            TestId = 10002
                        },
                        new
                        {
                            Id = 10206,
                            Content = "The writer believes remote work improves concentration.",
                            ContextText = "In my view, working from home can help people focus when they have a quiet workspace.",
                            GroupCode = "I-R2",
                            Order = 6,
                            PartNumber = 2,
                            QuestionType = "YesNoNotGiven",
                            SectionName = "Reading",
                            TestId = 10002
                        },
                        new
                        {
                            Id = 10207,
                            Content = "Complete the sentence: Solar panels convert sunlight into ____.",
                            ContextText = "Solar panels capture sunlight and convert it into electricity for homes and businesses.",
                            GroupCode = "I-R3",
                            Order = 7,
                            PartNumber = 3,
                            QuestionType = "FillBlank",
                            SectionName = "Reading",
                            TestId = 10002
                        });
                });

            modelBuilder.Entity("SKDJK.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "USER"
                        });
                });

            modelBuilder.Entity("SKDJK.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("tests", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 10001,
                            Description = "Bài luyện tập nội bộ mô phỏng cách chia Part của TOEIC Listening & Reading.",
                            DurationMinutes = 30,
                            Format = "ToeicStyle",
                            LessonId = 10001,
                            Title = "TOEIC-style Listening & Reading - Trung cấp"
                        },
                        new
                        {
                            Id = 10002,
                            Description = "Bài luyện tập nội bộ mô phỏng Listening và Reading của IELTS.",
                            DurationMinutes = 35,
                            Format = "IeltsStyle",
                            LessonId = 10003,
                            Title = "IELTS-style Listening & Reading - Cơ bản"
                        });
                });

            modelBuilder.Entity("SKDJK.Models.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("Datetime2");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.HasIndex("UserId");

                    b.ToTable("testresults", (string)null);
                });

            modelBuilder.Entity("SKDJK.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("topics", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 10001,
                            Description = "Từ vựng và kỹ năng giao tiếp trong các tình huống du lịch.",
                            ImageUrl = "/images/topic-travel.svg",
                            LanguageId = 10001,
                            Level = "Trung cấp",
                            Name = "Giao tiếp và du lịch"
                        },
                        new
                        {
                            Id = 10002,
                            Description = "Mẫu câu thường gặp trong học tập và công việc.",
                            ImageUrl = "/images/topic-work.svg",
                            LanguageId = 10001,
                            Level = "Cơ bản",
                            Name = "Học tập và công việc"
                        },
                        new
                        {
                            Id = 10003,
                            Description = "Các mẫu chào hỏi đơn giản.",
                            ImageUrl = "/images/topic-japanese.svg",
                            LanguageId = 10002,
                            Level = "Cơ bản",
                            Name = "Chào hỏi tiếng Nhật"
                        });
                });

            modelBuilder.Entity("SKDJK.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Bach1994@gmail.com",
                            FullName = "Nguyen Van Bach",
                            PasswordHash = "$2a$11$6yy1n7ZOuNvwVXiN78nTleFamsf5fpkodEtxod38CaHo9JRnpmQ8q",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "nguyenquangdiepnx1@gmail.com",
                            FullName = "Nguyen Quang Diep",
                            PasswordHash = "$2a$11$1S.ZcePBd3lvAcCg..i1beVY/fhIQD9QX4POW1zY.Xk1AhxT53RwW",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("SKDJK.Models.UserAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnswerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("TestResultId")
                        .HasColumnType("int");

                    b.Property<string>("TextAnswer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("TestResultId");

                    b.ToTable("useranswers", (string)null);
                });

            modelBuilder.Entity("SKDJK.Models.Vocabulary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("Example")
                        .HasColumnType("text");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Meaning")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Pronunciation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("vocabularies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 10001,
                            Example = "It was a long journey across the country.",
                            LessonId = 10001,
                            Meaning = "hành trình",
                            Pronunciation = "/ˈdʒɜːni/",
                            Word = "journey"
                        },
                        new
                        {
                            Id = 10002,
                            Example = "I have a reservation for two nights.",
                            LessonId = 10001,
                            Meaning = "đặt chỗ",
                            Pronunciation = "/ˌrezəˈveɪʃn/",
                            Word = "reservation"
                        },
                        new
                        {
                            Id = 10003,
                            Example = "Your luggage is beside the desk.",
                            LessonId = 10001,
                            Meaning = "hành lý",
                            Pronunciation = "/ˈlʌɡɪdʒ/",
                            Word = "luggage"
                        },
                        new
                        {
                            Id = 10004,
                            Example = "The station is near the hotel.",
                            LessonId = 10002,
                            Meaning = "nhà ga",
                            Pronunciation = "/ˈsteɪʃn/",
                            Word = "station"
                        },
                        new
                        {
                            Id = 10005,
                            Example = "Could you give me directions?",
                            LessonId = 10002,
                            Meaning = "phương hướng",
                            Pronunciation = "/dəˈrekʃn/",
                            Word = "direction"
                        },
                        new
                        {
                            Id = 10006,
                            Example = "The meeting starts at nine.",
                            LessonId = 10003,
                            Meaning = "cuộc họp",
                            Pronunciation = "/ˈmiːtɪŋ/",
                            Word = "meeting"
                        },
                        new
                        {
                            Id = 10007,
                            Example = "The deadline is Friday.",
                            LessonId = 10003,
                            Meaning = "hạn chót",
                            Pronunciation = "/ˈdedlaɪn/",
                            Word = "deadline"
                        },
                        new
                        {
                            Id = 10008,
                            Example = "Hello, nice to meet you.",
                            LessonId = 10004,
                            Meaning = "xin chào",
                            Pronunciation = "/həˈləʊ/",
                            Word = "hello"
                        });
                });

            modelBuilder.Entity("SKDJK.Models.Answer", b =>
                {
                    b.HasOne("SKDJK.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Answer_Question");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("SKDJK.Models.LearningProgress", b =>
                {
                    b.HasOne("SKDJK.Models.Lesson", "Lesson")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_LearningProgress_Lesson");

                    b.HasOne("SKDJK.Models.User", "User")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LearningProgress_User");

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SKDJK.Models.Lesson", b =>
                {
                    b.HasOne("SKDJK.Models.Topic", "Topic")
                        .WithMany("Lessons")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Topic_Lesson");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SKDJK.Models.PronunciationResult", b =>
                {
                    b.HasOne("SKDJK.Models.User", "User")
                        .WithMany("PronunciationResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PronunciationResult_User");

                    b.HasOne("SKDJK.Models.Vocabulary", "Vocabulary")
                        .WithMany("PronunciationResults")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_PronunciationResult_Vocabulary");

                    b.Navigation("User");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("SKDJK.Models.Question", b =>
                {
                    b.HasOne("SKDJK.Models.Test", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Question_Test");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("SKDJK.Models.Test", b =>
                {
                    b.HasOne("SKDJK.Models.Lesson", "Lesson")
                        .WithMany("Tests")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Test_Lesson");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("SKDJK.Models.TestResult", b =>
                {
                    b.HasOne("SKDJK.Models.Test", "Test")
                        .WithMany("TestResults")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TestResult_Test");

                    b.HasOne("SKDJK.Models.User", "User")
                        .WithMany("TestResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TestResult_User");

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SKDJK.Models.Topic", b =>
                {
                    b.HasOne("SKDJK.Models.Language", "Language")
                        .WithMany("Topics")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Language_Topic");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("SKDJK.Models.User", b =>
                {
                    b.HasOne("SKDJK.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_User_Role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SKDJK.Models.UserAnswer", b =>
                {
                    b.HasOne("SKDJK.Models.Answer", "Answer")
                        .WithMany("UserAnswers")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("FK_UserAnswer_Answer");

                    b.HasOne("SKDJK.Models.Question", "Question")
                        .WithMany("UserAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_UserAnswer_Question");

                    b.HasOne("SKDJK.Models.TestResult", "TestResult")
                        .WithMany("UserAnswers")
                        .HasForeignKey("TestResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserAnswer_TestResult");

                    b.Navigation("Answer");

                    b.Navigation("Question");

                    b.Navigation("TestResult");
                });

            modelBuilder.Entity("SKDJK.Models.Vocabulary", b =>
                {
                    b.HasOne("SKDJK.Models.Lesson", "Lesson")
                        .WithMany("Vocabularies")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Vocabulary_Lesson");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("SKDJK.Models.Answer", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("SKDJK.Models.Language", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("SKDJK.Models.Lesson", b =>
                {
                    b.Navigation("LearningProgresses");

                    b.Navigation("Tests");

                    b.Navigation("Vocabularies");
                });

            modelBuilder.Entity("SKDJK.Models.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("SKDJK.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SKDJK.Models.Test", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("SKDJK.Models.TestResult", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("SKDJK.Models.Topic", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("SKDJK.Models.User", b =>
                {
                    b.Navigation("LearningProgresses");

                    b.Navigation("PronunciationResults");

                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("SKDJK.Models.Vocabulary", b =>
                {
                    b.Navigation("PronunciationResults");
                });
#pragma warning restore 612, 618
        }
    }
}
