// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SKDJK.Data;

#nullable disable

namespace SKDJK.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260818101533_UpdateDatabase")]
    partial class UpdateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SKDJK.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("answers", (string)null);
                });

            modelBuilder.Entity("SKDJK.Models.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar")
                        .HasDefaultValue("English");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("SKDJK.Models.LearningProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CompletionPercent")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("LastStudyAt")
                        .HasColumnType("Datetime2");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar")
                        .HasDefaultValue("NOTSTARTED");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("learningprogresses", (string)null);
                });

            modelBuilder.Entity("SKDJK.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("lessons", (string)null);
                });

            modelBuilder.Entity("SKDJK.Models.PronunciationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VocabularyId");

                    b.ToTable("pronunciationresults", (string)null);
                });

            modelBuilder.Entity("SKDJK.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.ToTable("questions", (string)null);
                });

            modelBuilder.Entity("SKDJK.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoleName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            RoleName = "USER"
                        });
                });

            modelBuilder.Entity("SKDJK.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("tests", (string)null);
                });

            modelBuilder.Entity("SKDJK.Models.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("Datetime2");

                    b.Property<int>("TestId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestId");

                    b.HasIndex("UserId");

                    b.ToTable("testresults", (string)null);
                });

            modelBuilder.Entity("SKDJK.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("topics", (string)null);
                });

            modelBuilder.Entity("SKDJK.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Bach1994@gmail.com",
                            FullName = "Nguyen Van Bach",
                            PasswordHash = "$2a$11$6yy1n7ZOuNvwVXiN78nTleFamsf5fpkodEtxod38CaHo9JRnpmQ8q",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "nguyenquangdiepnx1@gmail.com",
                            FullName = "Nguyen Quang Diep",
                            PasswordHash = "$2a$11$1S.ZcePBd3lvAcCg..i1beVY/fhIQD9QX4POW1zY.Xk1AhxT53RwW",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("SKDJK.Models.Vocabulary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<string>("Example")
                        .HasColumnType("text");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Meaning")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Pronunciation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("vocabularies", (string)null);
                });

            modelBuilder.Entity("SKDJK.Models.Answer", b =>
                {
                    b.HasOne("SKDJK.Models.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Answer_Question");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("SKDJK.Models.LearningProgress", b =>
                {
                    b.HasOne("SKDJK.Models.Lesson", "Lesson")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_LearningProgress_Lesson");

                    b.HasOne("SKDJK.Models.User", "User")
                        .WithMany("LearningProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LearningProgress_User");

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SKDJK.Models.Lesson", b =>
                {
                    b.HasOne("SKDJK.Models.Topic", "Topic")
                        .WithMany("Lessons")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Topic_Lesson");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("SKDJK.Models.PronunciationResult", b =>
                {
                    b.HasOne("SKDJK.Models.User", "User")
                        .WithMany("PronunciationResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PronunciationResult_User");

                    b.HasOne("SKDJK.Models.Vocabulary", "Vocabulary")
                        .WithMany("PronunciationResults")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_PronunciationResult_Vocabulary");

                    b.Navigation("User");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("SKDJK.Models.Question", b =>
                {
                    b.HasOne("SKDJK.Models.Test", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Question_Test");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("SKDJK.Models.Test", b =>
                {
                    b.HasOne("SKDJK.Models.Lesson", "Lesson")
                        .WithMany("Tests")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_Test_Lesson");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("SKDJK.Models.TestResult", b =>
                {
                    b.HasOne("SKDJK.Models.Test", "Test")
                        .WithMany("TestResults")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_TestResult_Test");

                    b.HasOne("SKDJK.Models.User", "User")
                        .WithMany("TestResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TestResult_User");

                    b.Navigation("Test");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SKDJK.Models.Topic", b =>
                {
                    b.HasOne("SKDJK.Models.Language", "Language")
                        .WithMany("Topics")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Language_Topic");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("SKDJK.Models.User", b =>
                {
                    b.HasOne("SKDJK.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_User_Role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SKDJK.Models.Vocabulary", b =>
                {
                    b.HasOne("SKDJK.Models.Lesson", "Lesson")
                        .WithMany("Vocabularies")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Vocabulary_Lesson");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("SKDJK.Models.Language", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("SKDJK.Models.Lesson", b =>
                {
                    b.Navigation("LearningProgresses");

                    b.Navigation("Tests");

                    b.Navigation("Vocabularies");
                });

            modelBuilder.Entity("SKDJK.Models.Question", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("SKDJK.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SKDJK.Models.Test", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("SKDJK.Models.Topic", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("SKDJK.Models.User", b =>
                {
                    b.Navigation("LearningProgresses");

                    b.Navigation("PronunciationResults");

                    b.Navigation("TestResults");
                });

            modelBuilder.Entity("SKDJK.Models.Vocabulary", b =>
                {
                    b.Navigation("PronunciationResults");
                });
#pragma warning restore 612, 618
        }
    }
}
